### ISSUE TITLE
[DEPRECATED] Providers should implement the `boot(_: Droplet)` method to register dependencies. The `provided` property will be removed in a future update.

### ISSUE THREAD

**Issue by TofPlay** [vapor-community/postgresql-provider#13]
Hi,
When I run the server on Ubuntu I have this message:
```
# vapor run serve
Running ItWorks-PostgreSQL...
[DEPRECATED] Providers should implement the `boot(_: Droplet)` method to register dependencies. The `provided` property will be removed in a future update.
No preparations.
Server 'default' starting at 0.0.0.0:8080
```

**Comment by tanner0101** [comment]
Fixed in 1.1. https://github.com/vapor/postgresql-provider/releases/tag/1.1.1

**Comment by TofPlay** [comment]
Hi
I change my `Package.swit` like this:
```
# cat Package.swift
import PackageDescription

let package = Package(
    name: "ItWorks-PostgreSQL",
    dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", Version(1,2,0)),
        .Package(url: "https://github.com/vapor/postgresql-provider.git", Version(1,1,1))
    ],
    exclude: [
        "Config",
        "Database",
        "Localization",
        "Public",
        "Resources",
        "Tests",
    ]
)
```
When I try to build the project I have this message:
```
# vapor build
Fetching Dependencies [Failed]
Try cleaning your project first.
Error: swift-package: error: The dependency graph could not be satisfied because an update to `https://github.com/vapor/postgresql-provider.git' is required
```
If I specify:
``` 
 .Package(url: "https://github.com/vapor/postgresql-provider.git", Version(1,0,0))
```
I can build the project with the error on my first post

**Comment by tanner0101** [comment]
@TofPlay do `vapor build --clean`

**Comment by TofPlay** [comment]
```
root@02b33a183bca:/vapor/ItWorks-PostgreSQL# vapor build --clean
Cleaning [Done]
No Packages folder, fetch may take a while...
Fetching Dependencies [Done]
Building Project [Done]
root@02b33a183bca:/vapor/ItWorks-PostgreSQL# vapor run serve
Running ItWorks-PostgreSQL...
No preparations.
Server 'default' starting at 0.0.0.0:8080
```

@tannernelson  thanks 👍 😀

**Comment by a-malo** [comment]
```
^Camalo (master *) vapor_test $ vapor build --clean
Cleaning [Done]
No Packages folder, fetch may take a while...
Fetching Dependencies [Done]
Building Project [Done]
amalo (master *) vapor_test $ vapor run serve
Running vapor_test...
[DEPRECATED] Providers should implement the `boot(_: Droplet)` method to register dependencies. The `provided` property will be removed in a future update.
Database prepared
Server 'default' starting at 0.0.0.0:8080
```

I'm still getting the message. Using the mysql provider though.

**Comment by JasonhjKim** [comment]
@amalo95 Were u able to fix this problem?

**Comment by vzsg** [comment]
Guys, the postgresql-provider and the mysql-provider are two independent components, so if there's an issue with the latter, it should be asked there, not here.
